default_language_version:
  python: python3.9
repos:
# - repo: local
#   hooks:
#   - id: generate-parser
#     name: generate-parser
#     entry: ./generate-parser.py
#     language: python
#     files: '^grammar.lark$'
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
    exclude: '^src/rollit/grammar.g.py$'
  - id: detect-private-key
  - id: double-quote-string-fixer
    exclude: '^src/rollit/grammar.g.py$'
  - id: pretty-format-json
    args: ['--autofix', '--no-sort-keys', '--indent', '4', '--no-ensure-ascii']
  - id: trailing-whitespace
    exclude: '^src/rollit/grammar.py$'
- repo: https://github.com/pre-commit/mirrors-yapf.git
  rev: v0.29.0
  hooks:
  - id: yapf
    exclude: '^src/rollit/grammar.py$'
    args: ['-i', '-vv']
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.21.0
  hooks:
  - id: yamllint
- repo: https://github.com/jumanjihouse/pre-commit-hooks.git
  rev: 2.0.0
  hooks:
  - id: shellcheck
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety.git
  rev: v1.1.0
  hooks:
  - id: python-safety-dependencies-check
- repo: https://github.com/mattlqx/pre-commit-sign.git
  rev: v1.1.1
  hooks:
  - id: sign-commit
- repo: https://github.com/PyCQA/bandit.git
  rev: 1.6.2
  hooks:
  - id: bandit
    exclude: '^(tests/.*|src/rollit/grammar.g.py)$'
    args: ['-c', '.bandit']
- repo: https://github.com/PyCQA/pylint.git
  rev: pylint-2.4.4
  hooks:
  - id: pylint
    exclude: '^src/rollit/grammar.py$'
